version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - "cd /usr/bin"
      - "curl -O https://releases.hashicorp.com/terraform/0.12.7/terraform_0.12.7_linux_amd64.zip"
      - "unzip terraform_0.12.7_linux_amd64.zip"

  build:
    commands:
      - cd "$CODEBUILD_SRC_DIR"/dev
      - terraform init
      - terraform plan -out=plan.tfplan > /dev/null && terraform show -json plan.tfplan | curl -s -X POST -H "Content-Type: application/json" -d @- https://hooks.slack.com/services/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
      - terraform plan -out=terraform.out

post_build:
    commands:
      - echo "Terraform completed on `date`"

artifacts:
  files:
    - '**/*'
